// <auto-generated />
using System;
using Eva_Sxxi_Prepa_2025.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eva_Sxxi_Prepa_2025.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eva_Sxxi_Prepa_2025.Models.Alumno", b =>
                {
                    b.Property<string>("Matricula")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apellido2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Matricula");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("Eva_Sxxi_Prepa_2025.Models.Comentario", b =>
                {
                    b.Property<string>("ComentarioId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvaluacionTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenciaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComentarioId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("Eva_Sxxi_Prepa_2025.Models.Departamento", b =>
                {
                    b.Property<string>("DepartamentoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartamentoId");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("Eva_Sxxi_Prepa_2025.Models.Docente", b =>
                {
                    b.Property<string>("DocenteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocenteId");

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("Eva_Sxxi_Prepa_2025.Models.DocenteMateria", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DocenteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MateriaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DocenteMaterias");
                });

            modelBuilder.Entity("Eva_Sxxi_Prepa_2025.Models.Evaluacion", b =>
                {
                    b.Property<string>("EvaluacionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DocenteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MateriaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EvaluacionId");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("Eva_Sxxi_Prepa_2025.Models.EvaluacionDepartamento", b =>
                {
                    b.Property<string>("EvaluacionDepId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DepartamentoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EvaluacionDepId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("EvaluacionesDepartamentos");
                });

            modelBuilder.Entity("Eva_Sxxi_Prepa_2025.Models.Materia", b =>
                {
                    b.Property<string>("MateriaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MateriaId");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("Eva_Sxxi_Prepa_2025.Models.PreguntaDepartamento", b =>
                {
                    b.Property<string>("PreguntaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DepartamentoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PreguntaId");

                    b.ToTable("PreguntasDepartamentos");
                });

            modelBuilder.Entity("Eva_Sxxi_Prepa_2025.Models.PreguntaDocente", b =>
                {
                    b.Property<string>("PreguntaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PreguntaId");

                    b.ToTable("PreguntasDocentes");
                });

            modelBuilder.Entity("Eva_Sxxi_Prepa_2025.Models.RespuestaDepartamento", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EvaluacionDepId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PreguntaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvaluacionDepId");

                    b.ToTable("RespuestasDepartamento");
                });

            modelBuilder.Entity("Eva_Sxxi_Prepa_2025.Models.RespuestaDocente", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EvaluacionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EvaluacionId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("int");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvaluacionId");

                    b.HasIndex("EvaluacionId1");

                    b.ToTable("RespuestasDocente");
                });

            modelBuilder.Entity("Eva_Sxxi_Prepa_2025.Models.Usuario", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Eva_Sxxi_Prepa_2025.Models.EvaluacionDepartamento", b =>
                {
                    b.HasOne("Eva_Sxxi_Prepa_2025.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Eva_Sxxi_Prepa_2025.Models.RespuestaDepartamento", b =>
                {
                    b.HasOne("Eva_Sxxi_Prepa_2025.Models.EvaluacionDepartamento", "EvaluacionDepartamento")
                        .WithMany()
                        .HasForeignKey("EvaluacionDepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluacionDepartamento");
                });

            modelBuilder.Entity("Eva_Sxxi_Prepa_2025.Models.RespuestaDocente", b =>
                {
                    b.HasOne("Eva_Sxxi_Prepa_2025.Models.Evaluacion", "Evaluacion")
                        .WithMany()
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eva_Sxxi_Prepa_2025.Models.Evaluacion", null)
                        .WithMany("Respuestas")
                        .HasForeignKey("EvaluacionId1");

                    b.Navigation("Evaluacion");
                });

            modelBuilder.Entity("Eva_Sxxi_Prepa_2025.Models.Evaluacion", b =>
                {
                    b.Navigation("Respuestas");
                });
#pragma warning restore 612, 618
        }
    }
}
